version: "3.1"

services:
  db:
    image: postgres:13.7
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=backend

  backend:
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env